In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

In [2]:
import numpy as np
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [3]:
a = tf.constant(3.0,dtype=tf.float32)
b = tf.constant(4.0)#implicit tf.float32
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [17]:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())

In [6]:
sess = tf.Session()
print(sess.run(total))
print(sess.run({'ab':(a,b),'total':total}))

7.0
{'total': 7.0, 'ab': (3.0, 4.0)}


In [7]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1,out2)))

[0.574734   0.4163034  0.29582632]
[0.1580466 0.7683337 0.6976919]
(array([1.4599353, 1.8165283, 1.1555436], dtype=float32), array([2.4599352, 2.8165283, 2.1555436], dtype=float32))


In [9]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [12]:
print(sess.run(z,feed_dict={x:1,y:2}))
print(sess.run(z,feed_dict={x:[1,2],y:[3,4]}))

3.0
[4. 6.]


In [13]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [14]:
while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break

[0 1]
[2 3]
[4 5]
[6 7]


In [18]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

[1.2666831 2.2974498 1.6856279]
[ 1.1307071   0.18716468 -0.2105145 ]
[ 0.25692773 -0.10588226  0.20992926]
[-0.5376968   0.19089565 -0.00850342]
[ 0.34335142 -1.6524254  -1.1265342 ]
[ 0.074256   -0.42968604 -1.4404273 ]
[ 0.7598926  -0.47328383 -0.66764927]
[-0.54503506 -0.6005337   0.5987202 ]
[ 0.358301   -0.5517882   0.00696288]
[ 1.4136226   0.24318336 -0.35624066]


In [47]:
x = tf.placeholder(tf.float32, shape=[None,3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y,{x:[[1,2,3],[4,5,6],[7,8,9]]}))

[[ -3.4535062]
 [ -6.936869 ]
 [-10.420232 ]]


In [51]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

In [65]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))
print(sess.run(inputs))

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


# define the data

In [86]:
x = tf.constant(     [[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)
#this should end up being y = 1 - x

# define the model

In [87]:
linear_model = tf.layers.Dense(units=1)
y_pred = linear_model(x) #remember x is the input set
#and linear_model is the "function"

evaluate

In [88]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
sess.run(y_pred)

array([[-0.17346013],
       [-0.34692025],
       [-0.5203804 ],
       [-0.6938405 ]], dtype=float32)

That's great, but how's it going to get better?  
We need loss, training, and optimization

In [89]:
loss = tf.losses.mean_squared_error(labels=y_true,predictions=y_pred)
sess.run(loss)

1.9910619

In [90]:
optimizer = tf.train.GradientDescentOptimizer(0.01)#learning rate
train = optimizer.minimize(loss)

In [92]:
for i in range(100):
    _,loss_value = sess.run([train,loss])
    print(loss_value)

1.9910619
1.4476519
1.0701962
0.8078947
0.62549883
0.4985499
0.4100771
0.34830415
0.3050599
0.27467474
0.2532146
0.23794937
0.22698489
0.21900699
0.21310353
0.2086417
0.20518236
0.20242082
0.20014568
0.19821005
0.19651225
0.19498156
0.19356894
0.19224031
0.19097207
0.18974784
0.18855613
0.18738906
0.18624114
0.18510848
0.1839885
0.18287927
0.18177947
0.18068826
0.17960486
0.1785289
0.17746
0.17639798
0.1753426
0.17429377
0.17325136
0.17221525
0.17118543
0.17016184
0.16914438
0.16813305
0.1671278
0.16612852
0.16513525
0.1641479
0.1631665
0.16219094
0.1612212
0.1602573
0.15929912
0.15834671
0.1574
0.15645893
0.15552348
0.15459363
0.15366933
0.15275054
0.15183727
0.15092947
0.1500271
0.14913008
0.14823848
0.1473522
0.14647117
0.14559548
0.14472498
0.14385968
0.14299956
0.1421446
0.14129472
0.14044994
0.13961023
0.13877554
0.13794579
0.13712105
0.13630123
0.13548629
0.13467625
0.13387102
0.13307065
0.13227503
0.13148418
0.13069806
0.12991664
0.12913989
0.12836777
0.12760028
0.12683736
0.12

In [103]:
print(sess.run(y_pred))
print(sess.run(y_true))
print(sess.run(loss))

[[-0.56143004]
 [-1.2720513 ]
 [-1.9826727 ]
 [-2.693294  ]]
[[ 0.]
 [-1.]
 [-2.]
 [-3.]]
0.1208961
