In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

In [2]:
import numpy as np
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [3]:
a = tf.constant(3.0,dtype=tf.float32)
b = tf.constant(4.0)#implicit tf.float32
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [4]:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())

In [5]:
sess = tf.Session()
print(sess.run(total))
print(sess.run({'ab':(a,b),'total':total}))

7.0
{'total': 7.0, 'ab': (3.0, 4.0)}


In [6]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1,out2)))

[0.99965966 0.888132   0.8664329 ]
[0.62394214 0.4734888  0.63211894]
(array([1.8330115, 1.0034956, 1.9363738], dtype=float32), array([2.8330116, 2.0034957, 2.9363737], dtype=float32))


In [7]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [8]:
print(sess.run(z,feed_dict={x:1,y:2}))
print(sess.run(z,feed_dict={x:[1,2],y:[3,4]}))

3.0
[4. 6.]


In [9]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [10]:
while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break

[0 1]
[2 3]
[4 5]
[6 7]


In [11]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

[-0.41192955  0.7213786  -0.27270177]
[ 1.2672017   0.31904745 -0.16017973]
[-2.868603    0.7314694  -0.00400802]
[-0.61526966  2.282496   -0.9702167 ]
[-0.49414262 -0.48462796 -1.0142566 ]
[-0.91311574  0.2173991   0.16299313]
[-0.5454283   1.3852756   0.27343214]
[-1.1847446   0.86828417  0.95591545]
[-0.5604376   0.13206871 -1.644206  ]
[-0.98403466 -0.761815    0.94590783]


In [12]:
x = tf.placeholder(tf.float32, shape=[None,3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y,{x:[[1,2,3],[4,5,6],[7,8,9]]}))

[[2.6330552]
 [6.1669965]
 [9.700937 ]]


In [13]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

In [14]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))
print(sess.run(inputs))

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


# define the data

In [15]:
x = tf.constant(     [[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)
#this should end up being y = 1 - x

# define the model

In [16]:
linear_model = tf.layers.Dense(units=1)
y_pred = linear_model(x) #remember x is the input set
#and linear_model is the "function"

evaluate

In [17]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
sess.run(y_pred)

array([[0.8023013],
       [1.6046026],
       [2.4069037],
       [3.2092052]], dtype=float32)

That's great, but how's it going to get better?  
We need loss, training, and optimization

In [18]:
loss = tf.losses.mean_squared_error(labels=y_true,predictions=y_pred)
sess.run(loss)

16.350668

In [19]:
optimizer = tf.train.GradientDescentOptimizer(0.01)#learning rate
train = optimizer.minimize(loss)

In [20]:
for i in range(100):
    _,loss_value = sess.run([train,loss])
    print(loss_value)

16.350668
11.450159
8.049173
5.6886787
4.0501623
2.912615
2.1226835
1.5739589
1.1926059
0.9273927
0.74276984
0.61407024
0.5241784
0.46121788
0.41694796
0.38565055
0.36335796
0.34731698
0.3356175
0.32693356
0.3203457
0.31521556
0.31110024
0.30769235
0.3047787
0.30221117
0.2998872
0.29773542
0.2957063
0.2937656
0.29188937
0.29006094
0.28826904
0.28650552
0.28476477
0.28304294
0.28133726
0.27964592
0.27796754
0.27630112
0.27464604
0.2730018
0.27136812
0.26974458
0.2681311
0.26652753
0.26493362
0.2633494
0.26177466
0.2602095
0.25865367
0.25710717
0.25556993
0.2540419
0.25252295
0.25101313
0.24951236
0.24802059
0.24653769
0.24506369
0.24359849
0.24214205
0.2406943
0.23925525
0.23782481
0.23640287
0.23498943
0.23358445
0.23218791
0.23079969
0.2294198
0.22804812
0.22668466
0.22532935
0.22398213
0.22264297
0.22131182
0.21998863
0.21867338
0.21736597
0.21606635
0.21477455
0.21349043
0.21221404
0.21094523
0.209684
0.2084303
0.2071842
0.20594543
0.20471412
0.20349017
0.20227353
0.20106415
0.19986

In [21]:
print(sess.run(y_pred))
print(sess.run(y_true))
print(sess.run(loss))

[[-0.7068696]
 [-1.3425267]
 [-1.9781839]
 [-2.613841 ]]
[[ 0.]
 [-1.]
 [-2.]
 [-3.]]
0.19164595
